services:
  - type: web
    name: agent-trade-proxy-1
    runtime: python
    buildCommand: ""
    startCommand: uvicorn src.api.proxy_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
